### ISSUE TITLE
Related project - audreyt/ethercalc  

### ISSUE THREAD

**Issue by eddyparkinson** [keikai/keikai-tutorial#7]
Hi, sorry not sure where to post this.

Just letting you know about a related project: 
Examples: https://sheet.cellmaster.com.au/examples
code: https://github.com/audreyt/ethercalc

...
Speed and formulas - one issue I have found is people are using excel or google sheets and 
have lots of data in there sheets. They need a system that can handle a lot of data. But ethercalc gets slow with lots of data. .. Another issue is formulas, while some spreadsheets are fast, the often don't support many formulas, and yet existing excel/google user are using many formulas and want a spreadsheet that supports the same formulas. 

.... You look to have a HR use case from the demo, I am interested in use cases and the customer demand side. Do you know much about what end users are looking for?

**Comment by hawkchen** [comment]
Thanks for your feedback.

Keikai enterprise edition will be more efficient and support more formulas. We plan to release it in the next Feb, please tune on it. Since everyone has different expectation for speed, so you can test at your local site and feedback to us.

The demo case is just a simple case. We are good at creating a web spreadsheet component, but we don't know too much about HR system.
